### ISSUE TITLE
How to run the tool - >ipt_geofence: command not found

### ISSUE THREAD

**Issue by gelato-mio** [ntop/ipt_geofence#21]
Hi all,

I've followed the readme file and I've downloaded a db file and made some test config.json file, but whenever I use your command `ipt_geofence -c config.json -m dbip-country-lite.mmdb` I got that error that doesn't know what ipt_geofence command.

I think you have to be more explicit in order how to install properly the file. Could you please guide me on what next steps man should follow in order to test the tool? I think that the Instalation step should be edited and provide an additional steps with regards to the next commands we need to run in order to make the file, or the executable to be run so the tool will be installed properly.

Thank you in advance!

**Comment by frenzis01** [comment]
Hi! After cloning, try doing as follows, it worked for me:
`./autogen.sh`
`make`
`sudo sudo ipt_config_utils/single_iface.sh`
(place in the folder the db file and your config.json)
`sudo ./ipt_geofence -c config.json -m dbip-country-lite.mmdb`
Note the `./` before the command itself and make sure that the first three commands succeed.

**Comment by lucaderi** [comment]
@gelato-mio Is explanation enough? I will close the ticket, please reopen if necessary.
